name: render and push to website repo workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  render-and-push-to-website-repo-job:
    runs-on: ubuntu-latest

    steps:
      - name: clone this repo
        uses: actions/checkout@v2
        with:
          path: blog

      - name: clone website repo
        working-directory: ${{ github.workspace }}
        #uses: actions/checkout@v2
        #with:
        #  repository: shatsky/shatsky.github.io
        #  path: shatsky.github.io
        run: |
          git clone https://github.com/shatsky/shatsky.github.io.git

      - name: render posts
        working-directory: ${{ github.workspace }}/blog
        run: |
          rm -rf ${{ github.workspace }}/shatsky.github.io/posts
          sudo apt-get update
          sudo apt-get install -y cmark-gfm
          python3 ./build.py $GITHUB_WORKSPACE/shatsky.github.io/posts

      - name: push to website repo
        working-directory: ${{ github.workspace }}/shatsky.github.io
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add posts
          git commit -m "automatic push of rendered blog posts changes via github-actions upon push to blog repo"
          git push https://x-access-token:${{ secrets.WEBSITE_REPO_TOKEN }}@github.com/shatsky/shatsky.github.io.git
